Created migrations and its schema for the Job Portal Project
HarisButt090/Job-Portal-ROR pull request #2
Opened 2024-11-05 06:20 UTC by HarisButt090

### Description
This pull request include creating migrations for all tables, defining relations among them and creating its schema.

2024-11-06 14:04 UTC, 786minal requested changes

2024-11-06 14:04 UTC, minal-builds commented on db/migrate/20241105053633_create_users.rb
> +      t.references :company, null: false, foreign_key: true
kindly remove company reference as there is not need

2024-11-06 14:04 UTC, minal-builds commented on db/migrate/20241105053745_create_companies.rb
> +      t.string :company_name
change field name to **name** only
add user association in it

2024-11-06 14:04 UTC, 786minal commented on db/migrate/20241105054516_create_skills.rb
> +      t.string :skill_name
renamed this field to name only

2024-11-07 13:25 UTC, 786minal approved these changes

2024-11-08 07:07 UTC, merged

2024-11-08 07:07 UTC, 786minal approved these changes