Setup graphql to create API's
HarisButt090/Job-Portal-ROR pull request #25
Opened 2024-11-27 10:13 UTC by HarisButt090

This PR includes setting up graphql in current project and using graphiql-rails gem to have an interface to test.

2024-12-02 08:05 UTC, 786minal requested changes

2024-12-02 08:05 UTC, minal-builds commented on app/controllers/graphql_controller.rb
> +    result = FriendsSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
this isn't friend schema. kindly update this according to your App name

2024-12-02 08:05 UTC, minal-builds commented on app/graphql/friends_schema.rb
This will be jobportal schema file change  file name and it module name accordinly based on your app

2024-12-02 08:05 UTC, minal-builds commented on app/graphql/mutations/.keep
delete extra file that doesn't belongs to this PR

2024-12-02 08:05 UTC, minal-builds commented on app/graphql/types/.keep
delete extra file that doesn't belongs to this PR

2024-12-02 08:05 UTC, minal-builds commented on app/graphql/types/mutation_type.rb
> +    # TODO: remove me
remove test mutation as this PR for configuration of Graphql

2024-12-02 08:05 UTC, minal-builds commented on app/graphql/types/query_type.rb
> +    field :test_field, String, null: false,
remove Test query as this doesn't belongs to this PR

2024-12-02 08:05 UTC, 786minal commented on app/graphql/types/query_type.rb
> +    field :node, Types::NodeType, null: true, description: "Fetches an object given its ID." do
sync with me for this chunk updation

2024-12-02 08:05 UTC, 786minal commented on config/application.rb
>  module Friends
It will be JobPortal modlue as you app is not Firends app

2024-12-03 07:28 UTC, 786minal requested changes

2024-12-03 07:28 UTC, minal-builds commented on db/schema.rb
remove unessary change in this PR

2024-12-03 08:02 UTC, 786minal approved these changes

2024-12-03 08:02 UTC, merged